    on:
        push:
            branches:
                - master




    jobs:
        build:
            runs-on: ubuntu-latest
            
            steps:
                - name: 'Printing Folder contents(before)'
                  run: ls
                
                - uses: actions/checkout@v3   #to add docker file and java file 
                
                - name: 'Printing Folder contents(after)'
                  run: ls -a    #appear hidden files and unhidden files
